version: '3.2'
services:
  jenkins:
    image: jenkins
    volumes: 
      - /Users/m.zeineldin/Projects/project-B/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
  tomcat:
    image: tomcat 
    ports:
      - 9999:8080
    container_name: tomcat
    depends_on:
      - jenkins
    links:
      - jenkins
    volumes: 
      - /Users/m.zeineldin/Projects/project-B/jenkins/workspace/java/target:/usr/local/tomcat/webapps
