version: '3.2'
services:
  jenkins:
    image: jenkins
    volumes: 
      - /Users/m.zeineldin/Projects/project-B/jenkins:/var/jenkins_home
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins
  tomcat:
    image: tomcat 
    ports:
      - 9999:8080
    container_name: tomcat
    # volumes:
            #    - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system reboot.
            #  - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jenkins
    links:
      - jenkins
    volumes: 
      - /Users/m.zeineldin/Projects/project-B/jenkins/workspace/java/target:/usr/local/tomcat/webapps
        #volumes:
        #  /Users/m.zeineldin/Project/project-B/jenkins
